config/routes.rb
EVoucher::Application.routes.draw do
  devise_for :users, :skip => :registrations

  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Nuntium routes
  post '/nuntium/receive'

  root :to => 'home#index'

  resources :sites, except: [:destroy] do
    collection do
      get :search
    end

    member do
      get :assign_cards
      post :batch_assign_cards
      post :assign_individual_card
      post :return_cards

      get 'manager' => :edit_manager
      put 'manager' => :update_manager
      delete 'manager' => :destroy_manager
      post 'set_manager'

      get 'patients' => :patients
      get 'providers' => :providers
    end

    resources :clinics, except: [:new, :edit, :update] do
      member do
        get 'services'
        post 'toggle_service'
        post 'set_service_cost'
      end
    end

    resources :mentors, except: [:new, :update, :edit] do
      member do
        post 'add_patients'
        post 'auto_assign'
        post 'move_patients'
        post 'batch_validate'
      end
    end
  end

  resources :batches, :only => [:index, :show, :new, :create] do
    collection do
      get 'refresh'
    end
  end

  resources :cards, :only => [:show] do
    member do
      post 'start_validity'
      post 'set_expiration'
    end
  end

  resources :providers, :only => [:create, :destroy] do
    member do
      post 'toggle'
    end
  end

  resources :patients, :only => [:destroy] do
    member do
      post 'assign_card'
      post 'unassign_card'
      post 'deactivate_card'
    end
  end

  resources :transactions, :only => [:index] do
    member do
      post 'update_status'
    end
  end

  resources :statements, :only => [:index, :show, :destroy] do
    collection do
      get 'generate'
      post 'do_generate'
      post 'export'
    end
    member do
      post 'toggle_status'
    end
  end

  resources :activities, :only => [:index] do
  end

  resources :users, :except => [:show] do
  end

  resources :messages, :only => [:index] do
  end

  scope 'reports', :as => 'reports', :controller => :reports do
    get '/', to: redirect('/reports/card_allocation')
    get :card_allocation
    get :transactions
    get :services
    get :clinics
  end

  # for instedd-platform-rails
  get 'terms_and_conditions' => redirect("http://instedd.org/terms-of-service/")
end

app/views/shared/_logs_tabs.haml
%ul.logs-tabs.tabs.top
  %li.activities
    = link_to "Activity Log", activities_path
  %li.messages
    = link_to "Incoming SMSs", messages_path

.tabsline

:javascript
  $('.logs-tabs').find('.#{params[:controller]}').addClass('active');

app/views/shared/_reports_tabs.haml
%br
%ul.reports-tabs.tabs.top
  %li.card_allocation
    = link_to "Card Allocation", reports_card_allocation_path
  %li.transactions
    = link_to "Transactions", reports_transactions_path
  %li.services
    = link_to "Services", reports_services_path
  %li.clinics
    = link_to "Clinics", reports_clinics_path

.tabsline

:javascript
  $('.reports-tabs').find('.#{params[:action]}').addClass('active');

app/views/shared/_search_box.haml
- if policy(Site).search?
  .search-box
    = form_tag search_sites_path, method: 'get' do
      = search_field_tag :q, '', :placeholder => 'Search for AGEP IDs or Card SN', :class => 'ux-search w30'