config/routes.rb
EVoucher::Application.routes.draw do
  devise_for :users, :skip => :registrations

  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Nuntium routes
  post '/nuntium/receive'

  root :to => 'home#index'

  resources :sites, except: [:destroy] do
    collection do
      get :search
    end

    member do
      get :assign_cards
      post :batch_assign_cards
      post :assign_individual_card
      post :return_cards

      get 'manager' => :edit_manager
      put 'manager' => :update_manager
      delete 'manager' => :destroy_manager
      post 'set_manager'

      get 'patients' => :patients
      get 'providers' => :providers
    end

    resources :clinics, except: [:new, :edit, :update] do
      member do
        get 'services'
        post 'toggle_service'
        post 'set_service_cost'
      end
    end

    resources :mentors, except: [:new, :update, :edit] do
      member do
        post 'add_patients'
        post 'auto_assign'
        post 'move_patients'
        post 'batch_validate'
      end
    end
  end

  resources :batches, :only => [:index, :show, :new, :create] do
    collection do
      get 'refresh'
    end
  end

  resources :cards, :only => [:show] do
    member do
      post 'start_validity'
      post 'set_expiration'
    end
  end

  resources :providers, :only => [:create, :destroy] do
    member do
      post 'toggle'
    end
  end

  resources :patients, :only => [:destroy] do
    member do
      post 'assign_card'
      post 'unassign_card'
      post 'deactivate_card'
    end
  end

  resources :transactions, :only => [:index] do
    member do
      post 'update_status'
    end
  end

  resources :statements, :only => [:index, :show, :destroy] do
    collection do
      get 'generate'
      post 'do_generate'
      post 'export'
    end
    member do
      post 'toggle_status'
    end
  end

  resources :activities, :only => [:index] do
  end

  resources :users, :except => [:show] do
  end

  resources :messages, :only => [:index] do
  end

  scope 'reports', :as => 'reports', :controller => :reports do
    get '/', to: redirect('/reports/card_allocation')
    get :card_allocation
    get :transactions
    get :services
    get :clinics
  end

  # for instedd-platform-rails
  get 'terms_and_conditions' => redirect("http://instedd.org/terms-of-service/")
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  belongs_to :site

  has_many :patients

  validates_presence_of :name, :site
  validates_length_of :name, :maximum => 80

  before_destroy :check_no_patients

  def self.with_patient_counts
    joins(:patients, :site).group('mentors.id').
      select(['mentors.*', 'sites.name AS site_name',
              'COUNT(patients.id) AS patient_count',
              'COUNT(CASE WHEN patients.current_card_id IS NULL THEN 1 END) AS patients_without_card'])
  end

  private

  def check_no_patients
    if patients.count > 0
      errors[:base] << "Mentor has patients"
      false
    else
      true
    end
  end
end

app/models/mentor/csv_exporter.rb
class Mentor::CsvExporter < CsvExporter
  include CardsHelper

  def initialize(mentor)
    @mentor = mentor
  end

  def export
    headers "# AGEP ID", "Current Card", "Validity"
    generate do |csv|
      @mentor.patients.order(:agep_id).each do |patient|
        csv << [patient.agep_id, card_serial_number(patient.current_card), 
                patient.current_card.try(:validity)]
      end
    end
  end
end

app/controllers/mentors_controller.rb
class MentorsController < SiteController
  before_filter :load_mentor
  before_filter :add_breadcrumbs

  include ActionView::Helpers::TextHelper

  def index
    @mentors = policy_scope(@site.mentors).order(:name)

    respond_to do |format|
      format.html {
        @mentor = Mentor.new
        @mentor.site = @site
      }
      format.csv {
        exporter = Site::MentorsCsvExporter.new(@mentors)
        render_csv exporter.export, "#{@site.name}-mentors.csv"
      }
    end
  end

  def show
    respond_to do |format|
      format.html {
        @patients = @mentor.patients.includes(:current_card => :used_vouchers).order(:agep_id)
      }
      format.csv {
        exporter = Mentor::CsvExporter.new(@mentor)
        filename = "#{@mentor.name}-AGEP_IDs.csv"
        render_csv exporter.export, filename
      }
    end
  end

  def create
    @mentor = @site.mentors.create(mentor_params)
    if @mentor.valid?
      flash[:notice] = "Mentor added"
    end
    respond_to do |format|
      format.js
      format.html {
        redirect_to site_mentors_path(@site)
      }
    end
  end

  def destroy
    @mentor = @site.mentors.find(params[:id])
    @mentor.destroy
    if @mentor.destroyed?
      flash[:notice] = "Mentor was removed"
    else
      flash[:alert] = "Cannot remove mentor: #{@mentor.errors.full_messages.join}"
    end
    redirect_to site_mentors_path(@site)
  end

  def add_patients
    errors = []
    ids = params[:agep_ids].strip.split(/\s+/)
    ids.each do |agep_id|
      patient = @mentor.patients.create agep_id: agep_id
      unless patient.valid?
        errors << "#{agep_id} #{patient.errors[:agep_id].first}"
      end
    end
    if errors.empty?
      flash[:notice] = "#{ids.size} AGEP IDs added"
    else
      flash[:alert] = "Failed to add these IDs: #{errors.join(', ')}"
    end
    redirect_to site_mentor_path(@site, @mentor)
  end

  def auto_assign
    initial = params[:initial_serial_number]
    if initial
      cards = @site.unassigned_cards.where("serial_number >= ?", initial)
      if cards.count == 0
        flash[:alert] = "No unassigned cards found from #{initial}"
      else
        assigned = 0
        @mentor.patients.without_card.zip(cards).each do |(patient, card)|
          patient.current_card = card
          if patient.save
            assigned += 1
          end
        end
        flash[:notice] = "#{assigned} cards assigned"
      end
    else
      flash[:alert] = "No initial Serial Number specified"
    end
    redirect_to site_mentor_path(@site, @mentor)
  end

  def move_patients
    @target_mentor = Mentor.find(params[:target_id])
    Patient.transaction do
      ids = params[:patient_ids].split(',')
      ids.each do |id|
        patient = Patient.find(id)
        patient.update_attribute :mentor, @target_mentor
      end
      flash[:notice] = "#{ids.count} AGEP IDs moved to #{@target_mentor.name}"
    end
    redirect_to site_mentor_path(@site, @mentor)
  end

  def batch_validate
    Patient.transaction do
      success_count = 0
      error_count = 0

      ids = params[:patient_ids].split(',')
      ids.each do |id|
        card = Patient.find(id).current_card
        next if card.nil? or card.validated?
        card.validity = params[:validity]
        if card.save
          success_count += 1
        else
          error_count += 1
        end
      end

      notices = []
      notices << "#{pluralize(success_count, "card")} successfully validated." if success_count > 0
      notices << "#{pluralize(error_count, "card")} could not be validated." if error_count > 0
      if success_count == 0 and error_count == 0
        notices << "No cards were validated."
      end
      notice = notices.join(' ')
      if error_count > 0
        if success_count > 0
          flash[:alert] = notice
        else
          flash[:error] = notice
        end
      else
        flash[:notice] = notice
      end
    end
    redirect_to site_mentor_path(@site, @mentor)
  end

  private

  def load_mentor
    @mentor = @site.mentors.find(params[:id]) unless params[:id].blank?
    authorize @mentor || Mentor
  end

  def add_breadcrumbs
    @show_breadcrumb = true
    if current_user.admin?
      add_breadcrumb 'Sites', sites_path
      add_breadcrumb @site.name, site_path(@site)
    end
    add_breadcrumb 'Mentors', site_mentors_path(@site)
    if @mentor
      add_breadcrumb @mentor.name, site_mentor_path(@site, @mentor)
    end
  end

  def mentor_params
    params.require(:mentor).permit(:name)
  end
end

app/helpers/mentors_helper.rb
module MentorsHelper
  def first_unassigned_card_serial_number(site)
    site.unassigned_cards.first.try(:serial_number) 
  end

  def target_mentors_for_select(site, current = nil)
    options_for_select(site.mentors.order(:name).reject do |mentor|
      mentor == current
    end.map do |mentor|
      [mentor.name, mentor.id]
    end)
  end
end

app/views/mentors/_add_patients.haml
- if policy(@mentor).add_patients?
  .w30.ux-collapsible.collapsed(data-on-expanded="box grey")
    %span
      %a.fadd Add new AGEP IDs to this group
    .ux-content
      = form_tag add_patients_site_mentor_path(@site, @mentor) do
        .field.w30
          = label_tag :agep_ids, 'AGEP IDs'
          %p (you can enter several AGEP IDs separated by spaces or new lines)
          = text_area_tag :agep_ids, '', rows: 5, :autofocus => true
        .actions
          = button_tag 'Add', :class => 'grey'
          %a.cancel_action Cancel

app/views/mentors/_assign_card.haml
.dialog#assign_dialog
  .box.grey.w20
    %span
      %a.fadd Assign card
    .ux-content
      = form_tag nil, :method => "post", :remote => true do
        .field.w20
          %label(for="assign_sn") Serial Number
          %input.w20.serial_number#assign_sn(name="serial_number" type="text" data-focus="true")
        .actions
          %button.grey(type="submit") Assign

app/views/mentors/_auto_assign.haml
- if policy(@mentor).auto_assign?
  .w20.ux-collapsible.collapsed(data-on-expanded="box grey")
    %span.auto_assign_action
      %a.fsettings Assign cards automatically
    .ux-content
      = form_tag auto_assign_site_mentor_path(@site, @mentor) do
        .field.w20
          = label_tag :initial_serial_number, 'Initial Serial Number'
          = text_field_tag :initial_serial_number, nil,
            :class => 'serial_number', :autofocus => true
        .actions
          = button_tag 'Assign', :class => 'grey'
          %a.cancel_action Cancel

app/views/mentors/_batch_validate.haml
- if policy(@mentor).batch_validate?
  .w30.ux-collapsible.collapsed(data-on-expanded="box grey")
    %span.batch_validate_action
      %a.fplay.disabled Validate selected AGEP ID's cards
    .ux-content.batch_validate_dialog
      = form_tag batch_validate_site_mentor_path(@site, @mentor) do
        = hidden_field_tag "patient_ids", "", :id => "validate_patient_ids"
        .field.w30
          %label(for="batch_validity") Cards valid from
          %p (#{Date::HUMAN_DISPLAY_FORMAT} format)
          %input.w20.ux-datepicker#batch_validity(name="validity" type="text" data-focus="true" value="#{Date.today.to_human_param}" autocomplete="off")
        .actions
          = button_tag 'Validate', :class => 'grey'
          %a.cancel_action Cancel

app/views/mentors/_deactivate_card.haml
.dialog#report_dialog
  .box.grey.w20
    %span
      %a.fclaim Deactivate card
    .ux-content
      = form_tag nil, :method => "post", :remote => true do
        %p Please confirm the deactivation of the patient's card.
        %p
          %input#lost_card_check(type="checkbox" name="lost" value="1")
          %label(for="lost_card_check") Card was lost/stolen
        %p
          Serial Number
          %b.serial_number
        .actions
          %button.orange(type="submit") Deactivate

app/views/mentors/_destroy_patient.haml
.dialog#destroy_dialog
  .box.grey.w20
    %span
      %a.fdelete Remove
    .ux-content
      = form_tag nil, :method => "delete", :remote => true do
        %p Please confirm the removal of the patient from the system.
        .actions
          %button.orange(type="submit") Confirm Remove

app/views/mentors/_move_patients.haml
- if policy(@mentor).move_patients?
  .w30.ux-collapsible.collapsed(data-on-expanded="box grey")
    %span.move_patients_action
      %a.fright.disabled Move selected to another mentor
    .ux-content.move_dialog
      = form_tag move_patients_site_mentor_path(@site, @mentor) do
        = hidden_field_tag "patient_ids"
        .field.w30
          = label_tag :target_id, 'Select another mentor'
          = select_tag :target_id, target_mentors_for_select(@site, @mentor), include_blank: true, class: 'w30', autofocus: true
        .actions
          = button_tag 'Move', :class => 'grey', :disabled => true
          %a.cancel_action Cancel

app/views/mentors/_patient.haml
%tr(data-id="#{patient.id}")
  - if policy(patient).manage?
    %td
      = check_box_tag nil, patient.id, false, :class => 'patient_check'
  %td= patient.agep_id

  - if patient.current_card.nil?
    %td(colspan="3")
      - if policy(patient).assign_card?
        %span.noprint
          %a.fadd.assign_action(data-action="#{assign_card_patient_path(patient)}")
            Assign card
    %td.noprint(colspan="2")
  - else 
    %td
      = card_status(patient.current_card)
      %span= card_serial_number(patient.current_card)

    - if patient.current_card.validity.nil?
      %td.noprint(colspan="2")
        - if policy(patient.current_card).start_validity?
          %a.fplay.start_action(data-action="#{start_validity_card_path(patient.current_card)}") Start validity
    - else
      %td= card_validity(patient.current_card)
      %td
        = card_expiration(patient.current_card)
        - if patient.current_card.expiration.present? && policy(patient.current_card).set_expiration?
          %a.fedit.set_expiration(data-action="#{set_expiration_card_path(patient.current_card)}" data-expiration="#{patient.current_card.expiration.to_human_param}")

    %td.noprint
      - if policy(patient).deactivate_card?
        %a.fclaim.report_action(data-action="#{deactivate_card_patient_path(patient)}" data-serial-number="#{card_serial_number(patient.current_card)}") Deactivate card
    %td.noprint
      - if patient.can_unassign? && policy(patient).unassign_card?
        %a.fremove.unassign_action(data-action="#{unassign_card_patient_path(patient)}" data-serial-number="#{card_serial_number(patient.current_card)}") Unassign card
  %td.noprint
    - if patient.current_card.nil? && patient.can_be_destroyed? && policy(patient).destroy?
      %a.fdelete.destroy_action(data-action="#{patient_path(patient)}") Remove
    - else
      %a.fuser.hidden

app/views/mentors/_set_expiration.haml
.dialog#expiration_dialog
  .box.grey.w20
    %span
      %a.fedit Set card expiration
    .ux-content
      = form_tag nil, :method => "post", :remote => true do
        .field.w20
          %label(for="expiration") Expiration date
          %p (#{Date::HUMAN_DISPLAY_FORMAT} format)
          %input.w20.expiration.ux-datepicker#expiration(name="expiration" type="text" data-focus="true" value="#{(Date.today + 1.year).to_human_param}" autocomplete="off")
        .actions
          %button.grey(type="submit") Set

app/views/mentors/_start_validity.haml
.dialog#start_dialog
  .box.grey.w20
    %span
      %a.fplay Start validity
    .ux-content
      = form_tag nil, :method => "post", :remote => true do
        .field.w20
          %label(for="validity") Card is valid from
          %p (#{Date::HUMAN_DISPLAY_FORMAT} format)
          %input.w20.ux-datepicker#validity(name="validity" type="text" data-focus="true" value="#{Date.today.to_human_param}" autocomplete="off")
        .actions
          %button.grey(type="submit") Set

app/views/mentors/_unassign_card.haml
.dialog#unassign_dialog
  .box.grey.w20
    %span
      %a.fremove Unassign card
    .ux-content
      = form_tag nil, :method => "post", :remote => true do
        %p Please confirm you want to unassign the patient's card. It will be returned to the site's stock.
        %p
          Serial Number
          %b.serial_number
        .actions
          %button.orange(type="submit") Confirm Unassign

app/views/mentors/create.js.erb
<% if @mentor.valid? %>
  window.location.href = '<%=j site_mentors_path(@site); %>';
<% else %>
  $('#new_mentor').replaceWith('<%=j render partial: 'new_mentor' %>');
  $.status.showError('<%=j raw(error_messages_for(@mentor)) %>');
<% end %>

app/views/mentors/index.html.haml
- unless current_user.site_manager?
  = render partial: '/sites/tabs', locals: { active_tab: 'mentors' }
- else
  %h1= @site.name

%h1 Mentors

.tablewrapp.mentors.w60
  %table.GralTable.ItemTable
    %colgroup
      %col(style="width: auto")
      %col(style="width: 120px")
      %col.noprint(style="width: 140px")
    %tbody
      %tr
        %th Name
        %th AGEP IDs (without card)
        %th
      - @mentors.each do |mentor|
        %tr(data-action="#{site_mentor_path(@site, mentor)}")
          %td
            = mentor.name
          %td
            = mentor.patients.count
            - if mentor.patients.without_card.any?
              = "(#{mentor.patients.without_card.count})"
          %td
            = link_to '', site_mentor_path(@site, mentor), :class => 'farrow'
            - if policy(mentor).destroy?
              - if mentor.patients.count == 0
                = link_to 'Remove', site_mentor_path(@site, mentor), :method => :delete, :class => 'fdelete'
              - else
                %a.fdelete.disabled(title="Mentor can't be removed while she has patients assigned") Remove
      = render partial: 'new_mentor'

%br
.actions
  = link_to 'Export CSV', site_mentors_path(@site, :format => 'csv'), :class => 'fexport'

app/views/mentors/show.html.haml
- unless current_user.site_manager?
  = render partial: '/sites/tabs', locals: { active_tab: 'mentors' }
- else
  %h1.site= @site.name

%h2.mentor
  = link_to '', site_mentors_path(@site), :class => 'fleft'
  = @mentor.name

.tablewrapp.w90
  %table.GralTable.patients
    %colgroup
      - if policy(@mentor).move_patients?
        %col.noprint(style="width: 35px")
      %col(style="width: 110px")
      %col(style="width: 95px")
      %col(style="width: 100px")
      %col(style="width: 140px")
      %col.noprint(style="width: 140px")
      %col.noprint(style="width: auto")
      %col.noprint(style="width: 100px")
    %tr
      - if policy(@mentor).move_patients?
        %th
          %input.check_all(type="checkbox")
      %th AGEP ID
      %th Current card
      %th Valid from
      %th Expires
      %th(colspan="3")
    - @patients.each do |patient|
      = render partial: 'patient', locals: { patient: patient }

  = render partial: 'assign_card'
  = render partial: 'start_validity'
  = render partial: 'set_expiration'
  = render partial: 'deactivate_card'
  = render partial: 'unassign_card'
  = render partial: 'destroy_patient'

%br
.actions
  - if policy(@mentor).update?
    .column.w30
      = render partial: 'add_patients'
      = render partial: 'auto_assign'
      = render partial: 'batch_validate'
      = render partial: 'move_patients'
  .column.w30
    = link_to 'Export CSV', site_mentor_path(@site, @mentor, :format => 'csv'), :class => 'fexport'
    %br
    %a.fexport.print_self Print sheet

:javascript
  var NextSerialNumber = '#{first_unassigned_card_serial_number(@site)}';
  $(function() { onMentorShow() })