config/routes.rb
EVoucher::Application.routes.draw do
  devise_for :users, :skip => :registrations

  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Nuntium routes
  post '/nuntium/receive'

  root :to => 'home#index'

  resources :sites, except: [:destroy] do
    collection do
      get :search
    end

    member do
      get :assign_cards
      post :batch_assign_cards
      post :assign_individual_card
      post :return_cards

      get 'manager' => :edit_manager
      put 'manager' => :update_manager
      delete 'manager' => :destroy_manager
      post 'set_manager'

      get 'patients' => :patients
      get 'providers' => :providers
    end

    resources :clinics, except: [:new, :edit, :update] do
      member do
        get 'services'
        post 'toggle_service'
        post 'set_service_cost'
      end
    end

    resources :mentors, except: [:new, :update, :edit] do
      member do
        post 'add_patients'
        post 'auto_assign'
        post 'move_patients'
        post 'batch_validate'
      end
    end
  end

  resources :batches, :only => [:index, :show, :new, :create] do
    collection do
      get 'refresh'
    end
  end

  resources :cards, :only => [:show] do
    member do
      post 'start_validity'
      post 'set_expiration'
    end
  end

  resources :providers, :only => [:create, :destroy] do
    member do
      post 'toggle'
    end
  end

  resources :patients, :only => [:destroy] do
    member do
      post 'assign_card'
      post 'unassign_card'
      post 'deactivate_card'
    end
  end

  resources :transactions, :only => [:index] do
    member do
      post 'update_status'
    end
  end

  resources :statements, :only => [:index, :show, :destroy] do
    collection do
      get 'generate'
      post 'do_generate'
      post 'export'
    end
    member do
      post 'toggle_status'
    end
  end

  resources :activities, :only => [:index] do
  end

  resources :users, :except => [:show] do
  end

  resources :messages, :only => [:index] do
  end

  scope 'reports', :as => 'reports', :controller => :reports do
    get '/', to: redirect('/reports/card_allocation')
    get :card_allocation
    get :transactions
    get :services
    get :clinics
  end

  # for instedd-platform-rails
  get 'terms_and_conditions' => redirect("http://instedd.org/terms-of-service/")
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user
  has_many :clinics, :dependent => :destroy
  has_many :mentors, :dependent => :destroy
  has_many :patients, :through => :mentors
  has_many :cards, :dependent => :nullify
  has_many :providers, :through => :clinics

  scope :non_training, -> { where(:training => [nil, false]) }

  validates_presence_of :name
  validates_length_of :name, :maximum => 100

  def manager
    user
  end

  def unassigned_cards
    cards.where(:patient_id => nil).order(:serial_number)
  end

  def active_cards
    cards.where('cards.patient_id IS NOT NULL').where(:status => :active)
  end

  def self.with_patient_counts
    joins(:patients).group('sites.id').
      select(['sites.*',
              'COUNT(patients.id) AS patient_count',
              'COUNT(CASE WHEN patients.current_card_id IS NULL THEN 1 END) AS patients_without_card'])
  end
end

app/views/management/_mentors.haml
.tablewrapp.mentors
  %table.GralTable
    %tbody
      %tr
        %th Name
        %th Patients
        %th
      - @site.mentors.each do |mentor|
        %tr
          %td
            = link_to mentor.name, manage_site_mentor_path(@site, mentor)
          %td= mentor.patients.count
          %td
            = link_to '', manage_site_mentor_path(@site, mentor), :class => 'farrow'
            - if mentor.patients.count == 0
              = link_to 'Remove', site_mentor_path(@site, mentor), :method => :delete, :class => 'fdelete'

%br
.w30.ux-collapsible.collapsed(data-on-expanded="box grey")
  %span
    %a.fadd Add new Mentor
  .ux-content
    = form_tag site_mentors_path(@site) do
      .field
        = label_tag "mentor[name]", 'Name'
        = text_field_tag "mentor[name]", '', :class => 'w30'
      .actions
        = button_tag 'Add', :class => 'white'

app/views/management/_patients.haml
.tablewrapp
  %table.GralTable.patients
    %colgroup
      %col(style="width: 30px")
    %tr
      %th
      %th AGEP ID
      %th Current card
      %th Valid from
      %th
    - @mentor.patients.each do |patient|
      %tr(data-id="#{patient.id}")
        %td
          = check_box_tag nil, patient.id
        %td= patient.agep_id
        %td= card_serial_number(patient.current_card)
        %td= card_validity(patient.current_card)
        %td
          - if patient.current_card.nil?
            %a.fadd.assign_action(data-action="#{assign_card_patient_path(patient)}")
              Assign card
          - elsif patient.current_card.validity.nil?
            %a.fplay.start_action(data-action="#{start_validity_card_path(patient.current_card)}") Start validity
          - else
            %a.fclaim.report_action(data-action="#{lost_card_patient_path(patient)}" data-serial-number="#{card_serial_number(patient.current_card)}") Report lost

  .dialog#assign_dialog
    .box.grey.w20
      %span
        %a.fadd Assign card
      .ux-content
        = form_tag nil, :method => "post" do
          .field.w20
            %label(for="assign_sn") Serial Number
            %input.w20.serial_number#assign_sn(name="serial_number" type="text" data-focus="true" value="#{first_unassigned_card_serial_number(@site)}")
          .actions
            %button.white(type="submit") Assign

  .dialog#start_dialog
    .box.grey.w20
      %span
        %a.fplay Start validity
      .ux-content
        = form_tag nil, :method => "post" do
          .field.w20
            %label(for="validity") Card is valid from
            %input.w20.ux-datepicker#validity(name="validity" type="text" data-focus="true" value="#{Time.now.to_s(:date)}")
          .actions
            %button.white(type="submit") Set

  .dialog#report_dialog
    .box.grey.w20
      %span
        %a.fclaim Report lost
      .ux-content
        = form_tag nil, :method => "post" do
          %p Please confirm the patient's card was lost or stolen
          %p
            Serial Number
            %b.serial_number
          .actions
            %button.white(type="submit") Confirm Report

  

%br
.actions
  .w40.ux-collapsible.collapsed(data-on-expanded="box grey")
    %span
      %a.fadd Add new AGEP IDs to this group
    .ux-content
      = form_tag manage_site_add_patients_path(@site, @mentor) do
        .field.w40
          = label_tag :agep_ids, 'AGEP IDs'
          %p (you can enter several AGEP IDs separated by spaces or new lines)
          = text_area_tag :agep_ids, '', rows: 5, :autofocus => true
        .actions
          = button_tag 'Add', :class => 'white'

  - if @site.unassigned_cards.count > 0
    .w20.ux-collapsible.collapsed(data-on-expanded="box grey")
      %span
        %a.fsettings Assign cards automatically
      .ux-content
        = form_tag manage_site_auto_assign_path(@site, @mentor) do
          .field.w20
            = label_tag :initial_serial_number, 'Initial Serial Number'
            = text_field_tag :initial_serial_number, 
              first_unassigned_card_serial_number(@site), 
              :class => 'serial_number', :autofocus => true
          .actions
            = button_tag 'Assign', :class => 'white'
  - else
    .w20
      %span
        %a.fsettings.disabled Assign cards automatically


  .w30.ux-collapsible.collapsed(data-on-expanded="box grey")
    %span
      %a.fright Move selected to another mentor
    .ux-content.move_dialog
      = form_tag manage_site_move_patients_path(@site) do
        = hidden_field_tag "patient_ids"
        .field.w30
          = label_tag :target_id, 'Select another mentor'
          = select_tag :target_id, target_mentors_for_select(@site, @mentor), include_blank: true, class: 'w30', autofocus: true
        .actions
          = button_tag 'Move', :class => 'white', :disabled => true