config/routes.rb
EVoucher::Application.routes.draw do
  devise_for :users, :skip => :registrations

  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Nuntium routes
  post '/nuntium/receive'

  root :to => 'home#index'

  resources :sites, except: [:destroy] do
    collection do
      get :search
    end

    member do
      get :assign_cards
      post :batch_assign_cards
      post :assign_individual_card
      post :return_cards

      get 'manager' => :edit_manager
      put 'manager' => :update_manager
      delete 'manager' => :destroy_manager
      post 'set_manager'

      get 'patients' => :patients
      get 'providers' => :providers
    end

    resources :clinics, except: [:new, :edit, :update] do
      member do
        get 'services'
        post 'toggle_service'
        post 'set_service_cost'
      end
    end

    resources :mentors, except: [:new, :update, :edit] do
      member do
        post 'add_patients'
        post 'auto_assign'
        post 'move_patients'
        post 'batch_validate'
      end
    end
  end

  resources :batches, :only => [:index, :show, :new, :create] do
    collection do
      get 'refresh'
    end
  end

  resources :cards, :only => [:show] do
    member do
      post 'start_validity'
      post 'set_expiration'
    end
  end

  resources :providers, :only => [:create, :destroy] do
    member do
      post 'toggle'
    end
  end

  resources :patients, :only => [:destroy] do
    member do
      post 'assign_card'
      post 'unassign_card'
      post 'deactivate_card'
    end
  end

  resources :transactions, :only => [:index] do
    member do
      post 'update_status'
    end
  end

  resources :statements, :only => [:index, :show, :destroy] do
    collection do
      get 'generate'
      post 'do_generate'
      post 'export'
    end
    member do
      post 'toggle_status'
    end
  end

  resources :activities, :only => [:index] do
  end

  resources :users, :except => [:show] do
  end

  resources :messages, :only => [:index] do
  end

  scope 'reports', :as => 'reports', :controller => :reports do
    get '/', to: redirect('/reports/card_allocation')
    get :card_allocation
    get :transactions
    get :services
    get :clinics
  end

  # for instedd-platform-rails
  get 'terms_and_conditions' => redirect("http://instedd.org/terms-of-service/")
end

app/models/card.rb
class Card < ActiveRecord::Base
  extend Enumerize

  SERIAL_NUMBER_LENGTH = 6
  PRIMARY_SERVICES = 6
  SECONDARY_SERVICES = 7
  ANY_SERVICES = 12

  DEFAULT_VALIDITY = 1.year

  has_many :vouchers, :dependent => :destroy
  has_many :authorizations
  has_many :used_vouchers, ->{ where used: true }, :class_name => "Voucher"
  has_many :unused_vouchers, ->{ where used: false }, :class_name => "Voucher"

  belongs_to :patient
  belongs_to :site
  belongs_to :batch

  enumerize :status, in: [:active, :lost, :inactive], default: :active, predicates: true

  validates_presence_of :batch, :serial_number
  validates_uniqueness_of :serial_number
  validates_format_of :serial_number, :with => /\A[0-9]+\z/
  validates_length_of :serial_number, :is => SERIAL_NUMBER_LENGTH
  validate :valid_check_digit
  validate :validity_check

  before_save :set_expiration_from_validity

  def self.valid_serial_number?(sn)
    sn.length == SERIAL_NUMBER_LENGTH + 1 &&
      Card::Damm.generate(sn[1..-1]) == sn[0]
  end

  def self.find_by_serial_number(sn)
    if sn.to_s.length == SERIAL_NUMBER_LENGTH + 1
      self.where(serial_number: sn.to_s[1..-1], check_digit: sn.to_s[0]).first
    else
      self.where(serial_number: sn.to_serial_number).first
    end
  end

  def full_serial_number
    "#{check_digit}#{serial_number}"
  end

  def serial_number=(value)
    value = value.to_serial_number
    write_attribute :serial_number, value
    write_attribute :check_digit, Card::Damm.generate(value)
  end

  def primary_services
    vouchers.select { |v| v.primary? }
  end

  def secondary_services
    vouchers.select { |v| v.secondary? }
  end

  def any_services
    vouchers.select { |v| v.any? }
  end

  def expired?
    expiration.present? && expiration.past?
  end

  def depleted?
    !unused_vouchers.any?
  end

  def report_lost!
    update_attribute :status, :lost
  end

  def deactivate!
    update_attribute :status, :inactive
  end

  def unused_vouchers(type = nil)
    if type.nil?
      vouchers.where(:used => false)
    else
      vouchers.where(:used => false).where(:service_type => type)
    end
  end

  def used?
    used_vouchers.any? || authorizations.any?
  end

  def validated?
    validity.present?
  end

  def validity=(value)
    begin
      if value.nil?
        new_value = nil
      elsif value.is_a?(String)
        new_value = Date.parse_human_param(value) rescue Date.parse(value)
      elsif value.is_a?(Date) or value.is_a?(Time)
        new_value = value
      else
        raise ArgumentError, "invalid date value"
      end
      @invalid_date = false
      write_attribute :validity, new_value
    rescue
      @invalid_date = true
      write_attribute :validity, nil
    end
  end

  def expiration=(value)
    begin
      if value.nil?
        new_value = nil
      elsif value.is_a?(String)
        new_value = Date.parse_human_param(value) rescue Date.parse(value)
      elsif value.is_a?(Date) or value.is_a?(Time)
        new_value = value
      else
        raise ArgumentError, "invalid date value"
      end
      @invalid_expiration = false
      write_attribute :expiration, new_value
    rescue
      @invalid_expiration = true
    end
  end

  private

  def valid_check_digit
    unless check_digit == Card::Damm.generate(serial_number)
      errors[:check_digit] << "is invalid"
    end
  end

  def validity_check
    if @invalid_date
      errors[:validity] << "is invalid"
    elsif validity.present?
      if validity.future?
        errors[:validity] << "cannot be in the future"
      elsif validity.to_date < created_at.to_date
        errors[:validity] << "cannot be before the card was created"
      elsif expiration.present? && validity > expiration
        errors[:validity] << "cannot be after the expiration date"
      end
    end
  end

  def expiration_check
    if @invalid_expiration
      errors[:expiration] << "is invalid"
    elsif expiration.present?
      if expiration < validity
        errors[:expiration] << "cannot be before validity"
      end
    end
  end

  def set_expiration_from_validity
    if validity.present?
      self.expiration = validity + DEFAULT_VALIDITY if expiration.nil?
    else
      self.expiration = nil
    end
  end
end

app/models/card/code.rb
module Card::Code
  def self.generate(digits, options = {})
    if options.delete(:first_non_zero)
      (rand(9) + 1).to_s + self.generate(digits - 1, options)
    else
      digits.times.map { rand(10).to_s }.join
    end
  end

  def self.generate_with_check(digits, options = {})
    code = self.generate(digits - 1, options)
    code << Card::Damm.generate(code)
  end

  def self.check(code)
    Card::Damm.generate(code) == '0'
  end

  def self.generate_voucher_code
    self.generate_with_check(Voucher::VOUCHER_CODE_LENGTH, first_non_zero: true)
  end
end

app/models/card/damm.rb
module Card::Damm
  TASQ = [
    [0,3,1,7,5,9,8,6,4,2],
    [7,0,9,2,1,5,4,8,6,3],
    [4,2,0,6,8,7,1,3,5,9],
    [1,7,5,0,9,8,3,4,2,6],
    [6,1,2,3,0,4,5,9,7,8],
    [3,6,7,4,2,0,9,5,8,1],
    [5,8,6,9,7,2,0,1,3,4],
    [8,9,4,5,3,6,2,0,1,7],
    [9,4,3,8,6,1,7,2,0,5],
    [2,5,8,1,4,3,6,7,9,0],
  ]

  def self.generate(code)
    i = 0
    code.to_s.each_char { |d|
      i = TASQ[i][d.to_i]
    }
    i.to_s
  end
end

app/models/card/returner.rb
class Card::Returner
  def return_cards(ids)
    Card.transaction do
      cards = Card.where("patient_id IS NULL").where("id IN (?)", ids)
      cards.each do |card|
        card.update_attribute :site_id, nil
      end
      cards
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :load_card

  def show
  end

  def start_validity
    if @card.patient.nil?
      redirect_to root_path
      return
    end

    @card.validity = params[:validity]
    @card.save
    @patient = @card.patient
    respond_to do |format|
      format.js
      format.html {
        redirect_to site_mentor_path(@patient.site, @patient.mentor)
      }
    end
  end

  def set_expiration
    if @card.patient.nil?
      redirect_to root_path
      return
    end

    @card.expiration = params[:expiration]
    @card.save
    @patient = @card.patient
    respond_to do |format|
      format.js
      format.html {
        redirect_to site_mentor_path(@patient.site, @patient.mentor)
      }
    end
  end

  private

  def load_card
    @card = Card.find(params[:id])
    authorize @card
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def cards_availability(batches)
    batches.inject({}) do |result, batch|
      result[batch.id] = { 
        first_serial_number: batch.cards_available.first.try(:serial_number),
        quantity: batch.cards_available.count
      }
      result
    end
  end

  def card_status(card)
    if card
      if card.expired?
        content_tag(:span, '', :class => 'i18o-alert expired', :title => 'Card expired')
      elsif card.depleted?
        content_tag(:span, '', :class => 'i18g-alert depleted', :title => 'Card depleted')
      elsif card.lost? or card.inactive?
        content_tag(:span, '', :class => 'i18o-alert inactive', :title => 'Card deactivated')
      else
        ''
      end
    else
      ''
    end
  end

  def card_serial_number(card)
    if card
      "#{card.check_digit}-#{card.serial_number}"
    else
      ''
    end
  end

  def card_validity(card)
    if card && card.validity
      card.validity.in_time_zone.to_s(:date)
    else
      ''
    end
  end

  def card_expiration(card)
    if card && card.expiration
      card.expiration.in_time_zone.to_s(:date)
    else
      ''
    end
  end

  def transactions_for_card_path(card)
    txn_ids = card.authorizations.joins(:confirmation_txn).pluck('transactions.id')
    transactions_path(txn_id: txn_ids.join(','))
  end
end

app/views/cards/_unassigned_cards.haml
%h3 Cards in Site's stock not assigned to an AGEP ID

= form_tag site_cards_return_path(@site) do
  .unassigned_cards
    %table
      %thead
        %tr
          %th Batch
          %th Serial number
          %th
      %tbody
        - @site.unassigned_cards.each do |card|
          %tr
            %td= card.batch.name
            %td= card.serial_number
            %td
              = check_box_tag "return_ids[]", card.id, false, :class => 'return_card'
  .actions
    = submit_tag 'Return selected cards to PopCouncil stock'

app/views/cards/index.html.haml
%h1 Add Cards to Site Manager

%h2
  Site ID:
  = @site.name

.left
  .box.w50
    = render partial: 'site_status'

  %br
  .box.w50
    = render partial: 'add_from_batch'

  %br
  .box.w50
    = render partial: 'add_individual'

.right
  .box.w40
    = render partial: 'unassigned_cards'

.cards-span

:javascript
  var availability = #{cards_availability(@batches).to_json.gsub('</', '<\/')};
  $(function() { onCardsIndex() })

app/views/cards/set_expiration.js.erb
<% if @card.valid? %>
  $.status.showNotice('Card expiration set', 2000);
<% else %>
  $.status.showError('<%=j error_messages_for(@card) %>');
<% end %>
$('.patients').find('tr[data-id=<%= @patient.id %>]').replaceWith('<%=j render partial: '/mentors/patient', locals: { patient: @patient.reload } %>');

app/views/cards/show.html.haml
.card.box.w40
  %h2 Card #{card_serial_number(@card)}
  %p from batch #{@card.batch.name}

  %ul
    %li
      - if @card.site.nil?
        In Popcouncil stock.
      - else
        In site
        = link_to @card.site.name, @card.site

    %li
      - case @card.status
        - when 'active'
          - if @card.expired?
            The card is expired
          - elsif @card.depleted?
            %span.i18ny-alert
            The card is depleted
          - else
            The card is active
        - when 'lost'
          %span.i18o-alert
          The card was reported lost or stolen at #{@card.updated_at.localtime.to_s(:long)}
        - when 'inactive'
          %span.i18g-alert
          The card was deactivated #{@card.updated_at.localtime.to_s(:long)}

    %li
      - if @card.patient.nil?
        No AGEP ID assigned
      - elsif @card.patient.current_card_id == @card.id
        Currently assigned to AGEP ID
        = link_to @card.patient.agep_id, patient_in_mentor_path(@card.patient)
      - else
        Was assigned to AGEP ID
        = link_to @card.patient.agep_id, patient_in_mentor_path(@card.patient)

    %li
      - if @card.validated?
        - if @card.expired?
          %span.i18o-alert(title="expired")
        Valid from #{card_validity(@card)} thru #{card_expiration(@card)}
      - else
        Not validated yet

    %li
      - if !@card.used?
        Not used yet
      - else
        Used
        = link_to pluralize(@card.used_vouchers.count, 'time'), transactions_for_card_path(@card)

%br
.actions
  = link_to 'Back', :back

app/views/cards/start_validity.js.erb
<% if @card.valid? %>
  $.status.showNotice('Card validity set', 2000);
<% else %>
  $.status.showError('<%=j error_messages_for(@card) %>');
<% end %>
$('.patients').find('tr[data-id=<%= @patient.id %>]').replaceWith('<%=j render partial: '/mentors/patient', locals: { patient: @patient.reload } %>');